# Site information
site_name: Zone Mahdi &#9410
site_url: https://github.com/Mahdi-Moosa/mahdi-moosa.github.io
site_author: Mahdi Moosa
site_description: >-
  Mahdi Moosa's personal GitHub site. 

# Repository
repo_name: mahdi-moosa.github.io
repo_url: https://github.com/Mahdi-Moosa/mahdi-moosa.github.io

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
  palette: 
    
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue grey
      toggle:
        icon: material/brightness-7
        name: Switch to day mode

    # Palette toggle for light mode
    - scheme: default
      primary: grey
      toggle:
        icon: material/brightness-4 
        name: Switch to night mode
  
plugins:
  - blog:
      post_date_format: full
      # post_excerpt: required
      post_excerpt_separator: <!-- more -->
      post_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - tags:
      tags_file: tags.md
  - search:
      pipeline:
        - stemmer
        - stopWordFilter
        - trimmer

nav:
  - Home:
    - index.md
  - Blog:
    - blog/index.md
  - Tags:
    - tags.md
# nav not working for mobile devices.

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons  

extra:
  social:
    - icon: fontawesome/brands/google-scholar 
      link: https://scholar.google.com/citations?user=wbigX9EAAAAJ
    - icon: fontawesome/brands/researchgate 
      link: https://www.researchgate.net/profile/Mahdi-Moosa
    - icon: fontawesome/brands/square-github
      link: https://github.com/Mahdi-Moosa/
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.world/@mahdimoosa
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/mahdimoosa/
    # - icon: fontawesome/brands/firefox-browser
    # - icon: material/link 
    - icon: bootstrap/substack
      link: https://mahdimoosa.substack.com/


copyright: Copyright &copy; 2024 Mahdi Moosa